apiVersion: apps/v1
kind: Deployment
metadata:
  # define deployment name and the desired namespace
  name: webshop-api
  namespace: services
spec:
  # define the number of replicas. With this parameter we can scale the application.
  replicas: 1
  selector:
    matchLabels:
      bb: webshop-api
  template:
    metadata:
      labels:
        bb: webshop-api
    spec:
      containers:
        # define the container name and the image to use for the container. In this case our api image is hosted on docker hub.
        - name: webshop-api
          image: boudjemaa/webshop_api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 81